### PR TITLE
search: add support for searching document with namespace

### LINKED ISSUE #28: xmlua.Document:search() not work with namespace
```lua
local xml = require("xmlua").XML

local xml_str = [[
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationSuccess>
        <cas:user>241565750827950080</cas:user>
    </cas:authenticationSuccess>
</cas:serviceResponse>
]]

local document = xml.parse(xml_str)
local namespace = document:root():find_namespace(nil, "http://www.yale.edu/tp/cas")
print("namespace===" .. namespace:prefix())
local user = document:search("//cas:user")
print(user:to_xml())
```

Output:
```
namespace===cas
/usr/local/share/lua/5.1/xmlua/searchable.lua:70: Undefined namespace prefix
```

I thank it need to call `xmlXPathRegisterNs` method to register namespace in `Searchable:search()` function

### PR DESCRIPTION
**Pull request by komainu8**
GitHub: fix #28

Reported by GYWang1983. Thanks!!! 

If you want to use default namespace, you must specify namespaces explicitly.

### CODE REVIEW

File: xmlua/libxml2.lua [hunk 1]
```diff
@@ -471,6 +471,18 @@ function libxml2.xmlSearchNsByHref(document, node, href)
   return namespace
 end
 
+function libxml2.xmlFreeNsList(namespaces)
+  xml2.xmlFreeNsList(namespaces)
+end
```
Comment (kou) [inline xmlua/libxml2.lua:476]: Why do we need this?
How about using `xml2.xmlFreeNsList` directly?
